### ISSUE TITLE
Side effect in serializer breaks serialization

### ISSUE THREAD

**Issue by mausch** [elasticsearch/elasticsearch-net#1230]
The following program breaks unexpectedly:

```csharp
using Nest;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;
using System.IO;

class Program
{

    public enum Status
    {
        Closed = 7,
    }

    public class SearchModel
    {
        public Status Status { get; set; }
    }

    static void Deserialize()
    {
        var serializer = new NestSerializer(new ConnectionSettings());

        var rawResponse = @"
{
   ""took"": 20,
   ""timed_out"": false,
   ""_shards"": {
      ""total"": 5,
      ""successful"": 5,
      ""failed"": 0
   },
   ""hits"": {
      ""total"": 1,
      ""max_score"": 3.4727745,
      ""hits"": [
         {
            ""_index"": ""index"",
            ""_type"": ""index"",
            ""_id"": ""AUoptVGoUfrBUnDRG5ps"",
            ""_score"": 3.4727745,
            ""_source"": {
               ""status"": 7
            }
         }
      ]
   }
}
";

        using (var responseFile = new MemoryStream(Encoding.ASCII.GetBytes(rawResponse)))
        {
            // COMMENT OUT THE FOLLOWING LINE AND THE WHOLE TEST PASSES
            var response = serializer.Deserialize<SearchResponse<SearchModel>>(responseFile);
        }
    }

    static void Serialize()
    {
        var connSettings = new ConnectionSettings()
                    .AddContractJsonConverters(new Func<Type, JsonConverter>[]
                        {
                            EnumConverter,
                        });

        var serializer = new NestSerializer(connSettings);

        var bytes = serializer.Serialize(new SearchModel { Status = Status.Closed });
        var s = Encoding.UTF8.GetString(bytes);
        Console.WriteLine(s);
        var jobj = JToken.Parse(s);
        var value = jobj["status"].Value<string>();
        if (value != "Closed")
            throw new Exception("Expected Closed, was " + value);
    }

    static void Main(string[] args)
    {
        Deserialize();
        Serialize();
    }

    static JsonConverter EnumConverter(Type type)
    {
        if (type.IsEnum || (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>) && type.GetGenericArguments().First().IsEnum))
        {
            return new StringEnumConverter();
        }
        return null;
    }
}
```

This is a simplification of some actual test code I have in my current project which shows the same issue. In my code, `Deserialize()` is one test and `Serialize()` is another test. Since `Deserialize()` runs before `Serialize()`, something caches a **global** JSON converter or something for the `SearchModel` or `Status` types, which makes the subsequent serialization fail despite it being a new  instance of `NestSerializer` with specific JsonConverters defined.

It took me nearly an entire day to figure out what the problem was (there are lots of tests in this project) since there is no possible way to reason about such misbehavior (as is always the case with side-effects).

I haven't checked the code for NestSerializer yet but it seems that this serializer cache should be scoped to a NestSerializer instance instead of being a global mutable variable.

**Comment by Mpdreamz** [comment]
This is the way that Json.NET works

https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L203

We pass `shareCache` true, which is a massive performance gain since contracts for types only need to be resolved once. 

This is why we expose `AddContractJsonConverters` to be able to hook into this one time lookup. Historically we also had a separate `AddJsonConverters` for `per serializer instance` json converters but we removed this because it was just syntactic sugar over:

```csharp
.SetJsonSerializerSettingsModifier(s =>
{
    s.Converters = new JsonConverter[] {};
})				
```

Which would behave more as you'd expect it to. Json.NET will consult that array of converters for every node in the json graph. If you have too many of these there these can start to add up significantly to (de)serialization costs which is why we avoid setting any of our own `JsonConverters` here. 

The most preferred way to mark custom converters is to set a `JsonConverter` attribute on your types/properties as local as possible. These also become part of the contract and wont interfere with others. 

Failing that `AddContractJsonConverters`, provided you always pass the same set to each ConnectionSettings. 

Im sorry this took such a big chunk of your day today, I will update the xmldocs for `AddContractJsonConverters` to more explicitly state this behaviour.

**Comment by mausch** [comment]
Thanks for the explanation. Yeah, I thought this might be Newtonsoft's fault. Newtonsoft is littered with such broken "features" that just need to be avoided. It doesn't matter how fast they make things if they're broken.
Anyway this is a showstopper bug to me but it seems you're ok with this behavior, so it's probably not going to change in NEST so I'll just close this issue.

**Comment by Mpdreamz** [comment]
@mausch showstopper in what sense?

The reason why I am OK with this behaviour is because it is a performance gain. Perhaps it would be better if we explicitly made you register these in a static container but then it would be less discoverable and folks would rely on: 

```
.SetJsonSerializerSettingsModifier(s =>
{
    s.Converters = new JsonConverter[] {};
}) 
```

Perhaps not something we can change in our `1.x` releases but If you have thoughts on how we can improve for `2.0` I would love to hear them!

**Comment by mausch** [comment]
It's a showstopper for me in the sense that I can't really trust any code that does this and considers it a feature and therefore I won't use Elasticsearch.NET in any new projects or recommend it. Things are already hard enough to reason about with the serializer breaking parametricity, but this kind of side effects just makes it impossible.

The fix I'd apply is conceptually simple: don't share this cache in a global mutable variable, instead cache it in ConnectionSettings or NestSerializer. As you say, people don't generally use different ConnectionSettings so theoretically things shouldn't be very different. In practice to be honest I have no idea if this would be a big breaking change or what concretely this would mean to implement it, I realize it's only a very vague suggestion.

**Comment by Mpdreamz** [comment]
Thats a pity, as I said its the way json.net works and why we explicitly named the method `AddJsonContractConverters()` not `AddJsonConverters()`.

Thanks for all the feedback.

**Comment by mausch** [comment]
Yeah, Newtonsoft has tons of holes like that, which is why I prefer to use only JObject/JToken/etc with primitive types, and skip the rest.
Nevertheless, it's about *where* such code occurs. It would be generally bad to set the global `JsonConvert.DefaultSettings` in application code, but it would be a showstopper bug (just as I consider this one) to set that in library code. Library code absolutely needs to be more "encapsulated" (or "isolated").

**Comment by Mpdreamz** [comment]
Only here it pertains **only** to our contract resolver, which only this library uses. It wont break your manual `JsonConvert`'s in your application code or other libraries. Not claiming its not leaky but the extend of it is contained to **our** library code. 

The performance benefits are very real for us to open up the contract resolver cache like we do and I agree we need to better document this and the side effect free alternative (and the costs it associated with it).
