### ISSUE TITLE
Simplest way to add a AsciiFolding filter to Spanish language analyzer.

### ISSUE THREAD

**Issue by nataren** [elasticsearch/elasticsearch-net#1237]
Hello everyone:

Using NEST, I would like to add asciifolding to my Spanish analyzer. The way I am creating that analyzer is by subclassing the LanguageAnalyzer, and setting its Nest.Language according to a CultureInfo that receives as a parameter in its constructor.
```
public class CustomLanguageAnalyzer {
  public CustomLanguageAnalyzer(CultureInfo culture) 
    : base(GetNestLanguage(culture))
  {
  }
}
```
and it works pretty well, except that words that contain tildes like Español is not working for my Spanish analyzer. From what I understand I need to add the ```asciifolding``` filter to my custom Spanish analyzer, and I was wondering if there was a way I can re-use the filters that the spanish LanguageAnalyzer creates or if I have to re-create them somehow.

**Comment by gmarz** [comment]
Hi @nataren not sure I understand what you mean exactly by re-use the filters?

As you mentioned, first you'd have to add `asiifolding` to the list of filters.  Then you will need to update your index with the new analyzer, and then re-index your data to apply the new analysis.

It might be easier to just delete and re-create your index with the new analyzer since 1) you can't dynamically update an analyzer- you'll have to close the index first and 2) you have to re-index your data anyway.

Does that answer your question?

**Comment by nataren** [comment]
Hi @gmarz, thanks for the answer.
